linters-settings:
  disable:
    - staticcheck
    - govet
    - goanalysis_metalinter

  # Enable analyzers by name. Run `go tool vet help` to see all analyzers.
  enable:
    - asmdecl
    - assign
    - atomic
    - atomicalign
    - bools
    - buildtag
    - cgocall
    - composites
    - copylocks
    - deepequalerrors
    - errorsas
    - fieldalignment
    - findcall
    - framepointer
    - httpresponse
    - ifaceassert
    - loopclosure
    - lostcancel
    - nilfunc
    - nilness
    - nonamedreturns
    - printf
    - reflectvaluecompare
    - shadow
    - shift
    - sigchanyzer
    - sortslice
    - stdmethods
    - stringintconv
    - structtag
    - testinggoroutine
    - tests
    - unmarshal
    - unreachable
    - unsafeptr
    - unusedresult
    - unusedwrite

issues:
  exclude-rules:
    # All tests
    - path: _test\.go
      linters:
        - cyclop
        - exhaustivestruct
        - funlen
        - goerr113
        - lll
        - wrapcheck
        - staticcheck
    # Mockery-generated code — never hand-edit, never lint.
    - path: mocks/.*\.go
      linters:
        - all
