// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/epa-datos/epa-standards-backend/internal/pkg/entity"
	mock "github.com/stretchr/testify/mock"
)

// ExampleService is an autogenerated mock type for the ExampleService type
type ExampleService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, example
func (_m *ExampleService) Create(ctx context.Context, example *entity.Example) error {
	ret := _m.Called(ctx, example)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Example) error); ok {
		r0 = rf(ctx, example)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ExampleService) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ExampleService) GetByID(ctx context.Context, id string) (*entity.Example, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Example
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Example, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Example); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Example)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, offset, limit
func (_m *ExampleService) List(ctx context.Context, offset int64, limit int64) (*entity.ExamplesResponse, error) {
	ret := _m.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *entity.ExamplesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (*entity.ExamplesResponse, error)); ok {
		return rf(ctx, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) *entity.ExamplesResponse); ok {
		r0 = rf(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ExamplesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, example
func (_m *ExampleService) Update(ctx context.Context, id string, example *entity.Example) error {
	ret := _m.Called(ctx, id, example)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *entity.Example) error); ok {
		r0 = rf(ctx, id, example)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewExampleService creates a new instance of ExampleService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExampleService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExampleService {
	mock := &ExampleService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
